# Generated by Django 4.1 on 2023-02-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
